spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_library?useSSL=false&characterEncoding=utf-8
    username: root
    password: "000411"
    driver-class-name: com.mysql.cj.jdbc.Driver
  #  thymeleaf:
  #    cache: false
  mail:
    host: smtp.qq.com
    username: 792559738@qq.com
    password: fmafqfobckggbcia
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  #关于FreeMark的相关配置
  #模板引擎
  freemarker:
    request-context-attribute: request
    ##重要
    #关闭缓存
    cache: false
    #模板加载的位置
    template-loader-path: classpath:/templates/
    #后缀
    suffix: .ftl
    charset: UTF-8
    content-type: text/html
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    database: 0
#    timeout: 60s  # 数据库连接超时时间，springboot2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
#    # 连接池配置，springboot2.0中直接使用jedis或者lettuce配置连接池
#    jedis:
#      pool:
#        # 最大空闲连接数
#        max-idle: 500
#        # 最小空闲连接数
#        min-idle: 50
#        # 等待可用连接的最大时间，负数为不限制
#        max-wait:  -1s
#        # 最大活跃连接数，负数为不限制
#        max-active: -1

server:
  port: 8080
  servlet:
    session:
      timeout: 3000ms
  tomcat:
    uri-encoding: UTF-8
    max-threads: 100


#注意，这个节点不是在spring的节点下面的
mybatis:
  #对应mapper映射xml文件所在的路径
  mapper-locations: classpath:mapper/*.xml
  #对应实体类的路径
  type-aliases-package: com.example.demo.object

jwt:
  secret: mysecret
  tokenHeader: Authorization

pagehelper:
  reasonable: true
  helperDialect: mysql
  params: count=countSql
  support-methods-arguments: true
swagger:
  title: demo
  version: 1.0
